In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("C02_Emit.csv")

In [7]:
df.head()

   Country  Year                                             Series     Value
0  Albania  1975  Emissions (thousand metric tons of carbon diox...  4338.334
1  Albania  1985  Emissions (thousand metric tons of carbon diox...  6929.926
2  Albania  1995  Emissions (thousand metric tons of carbon diox...  1848.549
3  Albania  2005  Emissions (thousand metric tons of carbon diox...  3825.184
4  Albania  2010  Emissions (thousand metric tons of carbon diox...  3930.295

In [9]:
df.shape

(2132, 4)

In [10]:
df.columns

Index(['Country', 'Year', 'Series', 'Value'], dtype='object')

In [11]:
df.isnull().sum()

Country    0
Year       0
Series     0
Value      0
dtype: int64

In [12]:
df.isnull().mean() * 100

Country    0.0
Year       0.0
Series     0.0
Value      0.0
dtype: float64

In [15]:
df. dtypes

Country     object
Year         int64
Series      object
Value      float64
dtype: object

In [17]:
df["Series"].value_counts()

Series
Emissions (thousand metric tons of carbon dioxide)      1066
Emissions per capita (metric tons of carbon dioxide)    1066
Name: count, dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.describe()

              Year         Value
count  2132.000000  2.132000e+03
mean   2003.532833  9.147916e+04
std      14.096781  5.300037e+05
min    1975.000000  2.300000e-02
25%    1995.000000  3.254750e+00
50%    2010.000000  5.021550e+01
75%    2016.000000  2.355019e+04
max    2017.000000  9.257934e+06

In [21]:
df[df['Value'] < 0]

Empty DataFrame
Columns: [Country, Year, Series, Value]
Index: []

In [23]:
#for clear analysis, we separate total emissions and per-capita emissions

total_emissions = df[df["Series"].str.contains("total", case=False)]
per_capita_emissions = df[df["Series"].str.contains("per capita", case=False)]

In [25]:
pivot_total = total_emissions.pivot(
    index="Year",
    columns="Country",
    values="Value"
)

In [26]:
df.to_csv("CO2_Emit_Cleaned.csv", index=False)